"""fixes typo in the name column

Revision ID: ac7c1ce438e2
Revises: b57f5b5d3ac9
Create Date: 2025-06-18 16:57:21.885119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac7c1ce438e2'
down_revision = 'b57f5b5d3ac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=True))
        batch_op.drop_column('lastr_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastr_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###
