"""adds the first and last t name columns 

Revision ID: b57f5b5d3ac9
Revises: b28388612b10
Create Date: 2025-06-18 16:04:11.380643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b57f5b5d3ac9'
down_revision = 'b28388612b10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('lastr_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('lastr_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
